### ISSUE TITLE
Invalid install_requires configuration

### ISSUE THREAD

**Issue by moritz89** [urbanplatform/django-keycloak-auth#10]
Could it be that the current state of the `install_requires` in the `setup.cfg` file is invalid? Trying to install the current version of the package directly from Github results in an install failure. It seems to be from a [commit](https://github.com/urbanplatform/django-keycloak-auth/commit/bded4faf99bf11358c2189efeb1a85af05ea7ec0) that I introduced in the last MR.

A fix would be to use `>=` instead of `~=` in the `setup.cfg` file.

`pipenv install -e git+https://github.com/urbanplatform/django-keycloak-auth.git@master#egg=django_uw_keycloak`

```
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Installing -e git+https://github.com/urbanplatform/django-keycloak-auth.git@master#egg=django_uw_keycloak...
Error:  An error occurred while installing -e git+https://github.com/urbanplatform/django-keycloak-auth.git@master#egg=django_uw_keycloak!
Error text: Obtaining django_uw_keycloak from git+https://github.com/urbanplatform/django-keycloak-auth.git@master#egg=django_uw_keycloak (from -r /tmp/pipenv-_zrizod4-requirements/pipenv-tjpqe814-requirement.txt (line 1))
  Updating /home/moritz/.virtualenvs/core-FEar66-8/src/django-uw-keycloak clone (to revision master)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

  Running command git fetch -q --tags
  Running command git reset --hard -q 6dd764c3b6df785821fd9a60d3bbc7fbc76ec73e
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [43 lines of output]
      Traceback (most recent call last):
        File "/home/moritz/.virtualenvs/core-FEar66-8/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 102, in __init__
          req = REQUIREMENT.parseString(requirement_string)
        File "/home/moritz/.virtualenvs/core-FEar66-8/lib/python3.8/site-packages/pkg_resources/_vendor/pyparsing.py", line 1654, in parseString
          raise exc
        File "/home/moritz/.virtualenvs/core-FEar66-8/lib/python3.8/site-packages/pkg_resources/_vendor/pyparsing.py", line 1644, in parseString
          loc, tokens = self._parse( instring, 0 )
        File "/home/moritz/.virtualenvs/core-FEar66-8/lib/python3.8/site-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
          loc,tokens = self.parseImpl( instring, preloc, doActions )
        File "/home/moritz/.virtualenvs/core-FEar66-8/lib/python3.8/site-packages/pkg_resources/_vendor/pyparsing.py", line 3417, in parseImpl
          loc, exprtokens = e._parse( instring, loc, doActions )
        File "/home/moritz/.virtualenvs/core-FEar66-8/lib/python3.8/site-packages/pkg_resources/_vendor/pyparsing.py", line 1406, in _parseNoCache
          loc,tokens = self.parseImpl( instring, preloc, doActions )
        File "/home/moritz/.virtualenvs/core-FEar66-8/lib/python3.8/site-packages/pkg_resources/_vendor/pyparsing.py", line 3205, in parseImpl
          raise ParseException(instring, loc, self.errmsg, self)
      pkg_resources._vendor.pyparsing.ParseException: Expected stringEnd (at char 15), (line:1, col:16)
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/moritz/.virtualenvs/core-FEar66-8/src/django-uw-keycloak/setup.py", line 8, in <module>
          setup()
        File "/home/moritz/.virtualenvs/core-FEar66-8/lib/python3.8/site-packages/setuptools/__init__.py", line 152, in setup
          _install_setup_requires(attrs)
        File "/home/moritz/.virtualenvs/core-FEar66-8/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in _install_setup_requires
          dist.parse_config_files(ignore_option_errors=True)
        File "/home/moritz/.virtualenvs/core-FEar66-8/lib/python3.8/site-packages/_virtualenv.py", line 21, in parse_config_files
          result = old_parse_config_files(self, *args, **kwargs)
        File "/home/moritz/.virtualenvs/core-FEar66-8/lib/python3.8/site-packages/setuptools/dist.py", line 807, in parse_config_files
          self._finalize_requires()
        File "/home/moritz/.virtualenvs/core-FEar66-8/lib/python3.8/site-packages/setuptools/dist.py", line 534, in _finalize_requires
          self._move_install_requirements_markers()
        File "/home/moritz/.virtualenvs/core-FEar66-8/lib/python3.8/site-packages/setuptools/dist.py", line 573, in _move_install_requirements_markers
          inst_reqs = list(pkg_resources.parse_requirements(spec_inst_reqs))
        File "/home/moritz/.virtualenvs/core-FEar66-8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3099, in parse_requirements
          yield Requirement(line)
        File "/home/moritz/.virtualenvs/core-FEar66-8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3109, in __init__
          super(Requirement, self).__init__(requirement_string)
        File "/home/moritz/.virtualenvs/core-FEar66-8/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 104, in __init__
          raise InvalidRequirement(
      pkg_resources.extern.packaging.requirements.InvalidRequirement: Parse error at "'~= "3.0"'": Expected stringEnd
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

This is likely caused by a bug in django_uw_keycloak. Report this to its maintainers.
✘ Installation Failed
```

**Comment by ftcardoso** [comment]
Fixed with your suggestion
